# Generated by Django 4.2.11 on 2024-04-24 16:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="House",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="نام ساختمان")),
                ("title", models.CharField(max_length=200, verbose_name="عنوان")),
                ("address", models.CharField(max_length=255, verbose_name="آدرس")),
                ("price", models.TextField(verbose_name="قیمت")),
                ("bedrooms", models.IntegerField(verbose_name="تعداد اتاق\u200cها")),
                (
                    "bathrooms",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="سرویس بهداشتی"
                    ),
                ),
                ("parking_lot", models.BooleanField(verbose_name="پارکینگ")),
                (
                    "area",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="مساحت"
                    ),
                ),
                ("description", models.TextField(verbose_name="محتوا")),
                (
                    "image",
                    models.ImageField(upload_to="house_images/", verbose_name="تصویر"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("s", "فروش"), ("r", "اجاره")],
                        max_length=1,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("v", "ویلایی"), ("a", "آپارتمان")],
                        max_length=1,
                        verbose_name="نوع",
                    ),
                ),
                (
                    "publish",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="زمان انتشار"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ساخت"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "slug",
                    models.SlugField(
                        max_length=100, unique=True, verbose_name="آدرس مقاله"
                    ),
                ),
            ],
            options={
                "verbose_name": "خانه",
                "verbose_name_plural": "خانه ها",
            },
        ),
        migrations.CreateModel(
            name="HouseImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_path", models.ImageField(upload_to="house_images/")),
                ("caption", models.CharField(blank=True, max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "house",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="HouseService.house",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HouseDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feature", models.CharField(max_length=100)),
                ("year_built", models.IntegerField()),
                ("lot_size", models.DecimalField(decimal_places=2, max_digits=10)),
                ("garage_size", models.DecimalField(decimal_places=2, max_digits=10)),
                ("heating_type", models.CharField(max_length=100)),
                ("cooling_type", models.CharField(max_length=100)),
                ("other_details", models.TextField()),
                (
                    "house",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="HouseService.house",
                    ),
                ),
            ],
        ),
    ]
